In [1]:
import toy_data.cov_shift as data_gen
import toy_data as td
import bokeh.io
import numpy as np
import bokeh.plotting as bp
import bokeh.charts as bc
import matplotlib.pyplot as plt
import tensorflow as tf
bokeh.io.output_notebook()

<div class="bk-root">
        <a href="http://bokeh.pydata.org" target="_blank" class="bk-logo bk-logo-small bk-logo-notebook"></a>
        <span id="77fe642b-4df6-494c-841b-c1f9598b07c5">Loading BokehJS ...</span>
    </div>

<div class="bk-root">
        <a href="http://bokeh.pydata.org" target="_blank" class="bk-logo bk-logo-small bk-logo-notebook"></a>
        <span id="77fe642b-4df6-494c-841b-c1f9598b07c5">Loading BokehJS ...</span>
    </div>

In [3]:
# m_ = td.models.LinearBinary(2)
m_ = td.models.rotatedSine2D(phase=np.pi/2, frequency=1)
data = data_gen.Gaussian_Shift_2D_BinaryClassification(m_,
                                                       tst_X_mean_shift=(-3, -2.5),
                                                       noise_sd=0.4,
                                                       n_samples=400)
data_gen.visualize_2D_classification(data, classifyF=m_, fig_width=800)

<div class="bk-root">
        <div class="bk-plotdiv" id="ce643022-8a8f-4b12-b6a9-13620177ebde"></div>
    </div>
<script type="text/javascript">
  
  (function(global) {
    function now() {
      return new Date();
    }
  
    var force = false;
  
    if (typeof (window._bokeh_onload_callbacks) === "undefined" || force === true) {
      window._bokeh_onload_callbacks = [];
      window._bokeh_is_loading = undefined;
    }
  
  
    
    if (typeof (window._bokeh_timeout) === "undefined" || force === true) {
      window._bokeh_timeout = Date.now() + 0;
      window._bokeh_failed_load = false;
    }
  
    var NB_LOAD_WARNING = {'data': {'text/html':
       "<div style='background-color: #fdd'>\n"+
       "<p>\n"+
       "BokehJS does not appear to have successfully loaded. If loading BokehJS from CDN, this \n"+
       "may be due to a slow or bad network connection. Possible fixes:\n"+
       "</p>\n"+
       "<ul>\n"+
       "<li>re-rerun `output_notebook()` to attempt to load from CDN again, or</li>\n"+
       "<li>use INLINE resources instead, as so:</li>\n"+
       "</ul>\n"+
       "<code>\n"+
       "from bokeh.resources import INLINE\n"+
       "output_notebook(resources=INLINE)\n"+
       "</code>\n"+
       "</div>"}};
  
    function display_loaded() {
      if (window.Bokeh !== undefined) {
        var el = document.getElementById("ce643022-8a8f-4b12-b6a9-13620177ebde");
        el.textContent = "BokehJS " + Bokeh.version + " successfully loaded.";
      } else if (Date.now() < window._bokeh_timeout) {
        setTimeout(display_loaded, 100)
      }
    }
  
    function run_callbacks() {
      window._bokeh_onload_callbacks.forEach(function(callback) { callback() });
      delete window._bokeh_onload_callbacks
      console.info("Bokeh: all callbacks have finished");
    }
  
    function load_libs(js_urls, callback) {
      window._bokeh_onload_callbacks.push(callback);
      if (window._bokeh_is_loading > 0) {
        console.log("Bokeh: BokehJS is being loaded, scheduling callback at", now());
        return null;
      }
      if (js_urls == null || js_urls.length === 0) {
        run_callbacks();
        return null;
      }
      console.log("Bokeh: BokehJS not loaded, scheduling load and callback at", now());
      window._bokeh_is_loading = js_urls.length;
      for (var i = 0; i < js_urls.length; i++) {
        var url = js_urls[i];
        var s = document.createElement('script');
        s.src = url;
        s.async = false;
        s.onreadystatechange = s.onload = function() {
          window._bokeh_is_loading--;
          if (window._bokeh_is_loading === 0) {
            console.log("Bokeh: all BokehJS libraries loaded");
            run_callbacks()
          }
        };
        s.onerror = function() {
          console.warn("failed to load library " + url);
        };
        console.log("Bokeh: injecting script tag for BokehJS library: ", url);
        document.getElementsByTagName("head")[0].appendChild(s);
      }
    };var element = document.getElementById("ce643022-8a8f-4b12-b6a9-13620177ebde");
    if (element == null) {
      console.log("Bokeh: ERROR: autoload.js configured with elementid 'ce643022-8a8f-4b12-b6a9-13620177ebde' but no matching script tag was found. ")
      return false;
    }
  
    var js_urls = [];
  
    var inline_js = [
      function(Bokeh) {
        (function() {
          var fn = function() {
            var docs_json = {"34628ee8-0fbe-4cb0-b190-88750b7bfd0b":{"roots":{"references":[{"attributes":{"data_source":{"id":"92ab0c01-1203-4ead-8bd1-b842985f7ffc","type":"ColumnDataSource"},"glyph":{"id":"d92165db-a41d-446a-8614-c4cad7dfed69","type":"Cross"},"hover_glyph":null,"muted_glyph":null,"nonselection_glyph":{"id":"0c2eb647-a992-4e3b-a57a-451ff9a70014","type":"Cross"},"selection_glyph":null},"id":"f4351815-f67a-422f-ab9a-7acf5acd3104","type":"GlyphRenderer"},{"attributes":{"data_source":{"id":"68dcafd3-f29e-4f6b-9e4f-5ce1c0248747","type":"ColumnDataSource"},"gl

### RBA

#### Density estimation using logistic regression
\begin{align}
    \frac{P(X_{\text{tr}})}{P(X_{\text{tst}})} = \frac{P(X\mid s=\text{tr})}{P(X\mid s=\text{tst})}
    &= \frac{\frac{P(s=\text{tr}\mid X)P(X)}{P(s=\text{tr})}}{\frac{P(s=\text{tst}\mid X)P(X)}{P(s=\text{tst})}} \\
    &= \frac{P(s=\text{tr}\mid X)P(s=\text{tst})}{P(s=\text{tst}\mid X)P(s=\text{tr})} \\
    &= \frac{P(s=\text{tst})}{P(s=\text{tr})}\frac{1-P(s=\text{tst}\mid X)}{P(s=\text{tst}\mid X)} \\
    &= \frac{P(s=\text{tst})}{P(s=\text{tr})}(\frac{1}{P(s=\text{tst}\mid X)} - 1)
\end{align}

Hence we can find $P(s=\text{tst}\mid X)$ first and then calculate the ratio from it
\begin{align}
\text{minimize}_{w} -\log p(s=\text{tst}\mid x; w),
\end{align}
which is logistic regression on $x, s$

A simplified version of the ratio is
\begin{align}
    &\frac{P(s=\text{tst})}{P(s=\text{tr})}(\frac{1}{P(s=\text{tst}\mid X)} - 1) \\
    &=\frac{P(s=\text{tst})}{P(s=\text{tr})}(\frac{1}{\text{sigmoid}(-wX)} - 1) \\
    &=\frac{P(s=\text{tst})}{P(s=\text{tr})}e^{-wX}
\end{align}

In [5]:
tr = data.tr
tst = data.tst

In [8]:
n_tr = tr.y.shape[0]
n_tst = tst.y.shape[0]

x = tf.placeholder(tf.float32, [None, 2])
W = tf.Variable(tf.random_uniform(shape=[2, 1]), dtype=tf.float32)
b = tf.Variable(tf.random_uniform(shape=[1]), dtype=tf.float32)
logits = tf.matmul(x, W) + b
y = tf.nn.sigmoid(logits)
y_ = tf.placeholder(tf.float32, [None, 1])

cross_entropy = tf.nn.sigmoid_cross_entropy_with_logits(logits=logits, labels=y_)
# loss = tf.reduce_mean(cross_entropy + tf.nn.l2_loss(W))
loss = tf.reduce_mean(cross_entropy)
train_step = tf.train.RMSPropOptimizer(0.01).minimize(cross_entropy)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

s = np.concatenate((np.zeros(n_tr), np.ones(n_tst))).reshape(-1, 1)

for i in range(1000):
    sess.run(train_step, feed_dict={x: np.vstack((tr.X, tst.X)), y_: s})

correct_prediction = tf.equal(y > 0.5, y_ > 0.5)
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(sess.run(loss, feed_dict={x: np.vstack((tr.X, tst.X)), y_: s}))
print(sess.run(accuracy, feed_dict={x: np.vstack((tr.X, tst.X)), y_: s}))

def logi_classify_F(X):
    return sess.run(y, feed_dict={x: X})

data_gen.visualize_2D_classification(data, classifyF=logi_classify_F, fig_width=400)

0.164329
0.92


In [9]:
def logi_reweight_F(X):
    _R = sess.run(n_tst/n_tr*(tf.exp(logits)), feed_dict={x: X})
    # _R = sess.run(n_tst/n_tr*(tf.exp(-logits)), feed_dict={x: X})
    return _R

plt.hist(-1/logi_reweight_F(data.tst.X))
plt.show()

array([[ 0.0022937]], dtype=float32)

In [10]:
def mixed_moments_tf(_t, order):
    if order == 1:
        return _t
    n_vars = _t.get_shape()[1]
    r = [tf.expand_dims(_t[:, i], axis=1) * mixed_moments_tf(_t[:, i:], order - 1) for i in range(n_vars)]
    return tf.concat(r, axis=1)


def get_moments(_x, order):
    # The hack by https://github.com/tensorflow/tensorflow/issues/956
    _t = tf.pad(_x - 1, [[0, 0], [1, 0]], 'CONSTANT') + 1
    return mixed_moments_tf(_t, order)

var_x = tf.Variable(tr.X)
moment_x = get_moments(var_x, 3)
with tf.Session() as _sess:
    _sess.run(var_x.initializer)
    momentx = _sess.run(moment_x)

In [147]:
n_classes = 2
ys = np.eye(n_classes)

In [53]:
tr_y_1hot = np.hstack((tr.y, 1 - tr.y))
m_tr = get_moments(tr.X, 1).T
m_tr = m_tr[:, :, np.newaxis, np.newaxis]
# tr_y_1hot.shape
tr_y_1hot_4D = tr_y_1hot[:, np.newaxis, :, np.newaxis]
m_tr.shape

(320, 10, 1, 1)

In [55]:
min_eps = 0.0001
max_iter = 10000
lr = 0.0001
l_theta = 0.5
theta = np.zeros((10, n_classes))

In [56]:
def softmax(x, max_dim):
    e_x = np.exp(x - np.max(x, axis=max_dim, keepdims=True))
    return e_x / e_x.sum(axis=max_dim, keepdims=True)

def RBA_predict(x, theta):
    m = get_moments(x, 1).T
    m_d = m[:,:, np.newaxis, np.newaxis]*ys[np.newaxis, np.newaxis, :, :]
    # m_d.shape = (n_data, n_moments, n_classes, n_classes)
    pm_c = -1/logi_reweight_F(x)[:, :, np.newaxis, np.newaxis]*m_d*theta[np.newaxis, :, :, np.newaxis]
    p_c = np.sum(pm_c, axis=1, keepdims=True)
    return softmax(p_c, 3)

m_all = get_moments(data.X, 1).T
m_d_all = m_all[:,:, np.newaxis, np.newaxis]*ys[np.newaxis, np.newaxis, :, :]
reweight_all = logi_reweight_F(data.X)
def RBA_predict_all(theta):
    pm_c = -1/reweight_all[:, :, np.newaxis, np.newaxis]*m_d_all*theta[np.newaxis, :, :, np.newaxis]
    p_c = np.sum(pm_c, axis=1, keepdims=True)
    return softmax(p_c, 3)
    
def E(_m, _p):
    _Em = np.mean(_m*_p, axis=0)
    return np.sum(_Em, axis=2)

E_m_tr = E(m_tr, tr_y_1hot_4D)
    
_iter = 0
while True:
    _iter += 1
    pred = RBA_predict_all(theta) 
    dL = E_m_tr - E(m_d_all, pred)
    regular_grad = 2*theta/(np.linalg.norm(theta.ravel()) + 1e-9)
    theta_inc = dL + l_theta*regular_grad
    theta -= lr * theta_inc
    eps = np.linalg.norm(theta_inc)
    if not (_iter % 1000): # and _iter % 1001 and _iter % 1002):
        print(eps, np.linalg.norm(theta.ravel()))
        # print(theta.T)
        # print(l_theta*regular_grad.T)
    if eps < min_eps or _iter >= max_iter: 
        break

1.28141329014 0.193215180298
0.963090619519 0.299807172456
0.816176745168 0.384969706563
0.730676461198 0.459158772167
0.669735271353 0.526288277083
0.631046167804 0.588601319132
0.597335416497 0.647357477916
0.567987928567 0.703295806892
0.545740380213 0.756841163025
0.525501152991 0.808457814335


In [57]:
def RBA_F(x):
    pred = RBA_predict(x, theta)
    np.set_printoptions(precision=2, suppress=True)
    print(pred[0:5,0,:,:])
    np.set_printoptions(precision=8, suppress=False)
    print(pred.shape)
    
    return pred[:, 0, 0, 0]
data_gen.visualize_2D_classification(data, classifyF=RBA_F, fig_width=600)

[[[ 0.47  0.53]
  [ 0.51  0.49]]

 [[ 0.47  0.53]
  [ 0.51  0.49]]

 [[ 0.47  0.53]
  [ 0.51  0.49]]

 [[ 0.46  0.54]
  [ 0.51  0.49]]

 [[ 0.46  0.54]
  [ 0.51  0.49]]]
(22500, 1, 2, 2)
